import {
  Link2,
  Globe,
  ExternalLink,
  Home,
  Rss,
  Bell,
  Clock,
  Bookmark,
  Tag,
  Flag,
  Star,
  Heart,
  Sparkles,
  Zap,
  Flame,
  Award,
  Trophy,
  Crown,
  User,
  Users,
  Mail,
  MessageCircle,
  Send,
  Phone,
  MapPin,
  Map,
  Compass,
  Store,
  ShoppingBag,
  ShoppingCart,
  Gift,
  Package,
  CreditCard,
  DollarSign,
  Wallet,
  Bitcoin,
  TrendingUp,
  BarChart3,
  PieChart,
  Ticket,
  Briefcase,
  Music,
  Video,
  Play,
  Film,
  Camera,
  Image as ImageIcon,
  Headphones,
  Radio,
  Podcast,
  Tv,
  Disc,
  Mic,
  BookOpen,
  Newspaper,
  FileText,
  PenTool,
  Palette,
  Brush,
  Feather,
  Code,
  Terminal,
  Github,
  GitBranch,
  Database,
  Cloud,
  Server,
  Rocket,
  Bug,
  Settings,
  Wrench,
  Cpu,
  Calendar,
  Coffee,
  Utensils,
  Wine,
  Dumbbell,
  Activity,
  Leaf,
  Sun,
  Moon,
  Building2,
  Landmark,
  Plane,
  Car,
  Smile,
  ThumbsUp,
  Handshake,
  Megaphone,
  Gamepad2,
  type LucideIcon,
} from 'lucide-react'

export const LINK_ICONS: Record<string, LucideIcon> = {
  link: Link2,
  globe: Globe,
  'external-link': ExternalLink,
  home: Home,
  rss: Rss,
  bell: Bell,
  clock: Clock,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,
  star: Star,
  heart: Heart,
  sparkles: Sparkles,
  zap: Zap,
  flame: Flame,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  user: User,
  users: Users,
  mail: Mail,
  message: MessageCircle,
  send: Send,
  phone: Phone,
  'map-pin': MapPin,
  map: Map,
  compass: Compass,
  store: Store,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  package: Package,
  'credit-card': CreditCard,
  dollar: DollarSign,
  wallet: Wallet,
  bitcoin: Bitcoin,
  'trending-up': TrendingUp,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  ticket: Ticket,
  briefcase: Briefcase,
  music: Music,
  video: Video,
  play: Play,
  film: Film,
  camera: Camera,
  image: ImageIcon,
  headphones: Headphones,
  radio: Radio,
  podcast: Podcast,
  tv: Tv,
  disc: Disc,
  mic: Mic,
  book: BookOpen,
  newspaper: Newspaper,
  file: FileText,
  pen: PenTool,
  palette: Palette,
  brush: Brush,
  feather: Feather,
  code: Code,
  terminal: Terminal,
  github: Github,
  'git-branch': GitBranch,
  database: Database,
  cloud: Cloud,
  server: Server,
  rocket: Rocket,
  bug: Bug,
  settings: Settings,
  wrench: Wrench,
  cpu: Cpu,
  calendar: Calendar,
  coffee: Coffee,
  utensils: Utensils,
  wine: Wine,
  dumbbell: Dumbbell,
  activity: Activity,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  building: Building2,
  landmark: Landmark,
  plane: Plane,
  car: Car,
  smile: Smile,
  'thumbs-up': ThumbsUp,
  handshake: Handshake,
  megaphone: Megaphone,
  game: Gamepad2,
}

export const LINK_ICON_KEYS = Object.keys(LINK_ICONS)

export function faviconSources(url: string): string[] {
  try {
    const { origin } = new URL(url)
    return [
      `https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=${encodeURIComponent(origin)}&size=64`,
      `${origin}/favicon.ico`,
    ]
  } catch {
    return []
  }
}
